### ISSUE TITLE
Implement CI/CD flow

### ISSUE THREAD

**Issue by MufasaTheMusician** [MufasaTheMusician/eatwithme#14]
-Use Codemagic

**Comment by MufasaTheMusician** [comment]
Shadows have shown interest in helping us user test, so when we have the dev pipeline set up, we could give them access to those APKs

**Comment by ttww97** [comment]
- [ ] Build Android workflow

- [ ] Build iOS workflow

- [ ] Test two branches and pull requests

- [ ] Testing unit tests

- [ ] Releasing to app stores
