### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Joel-Groves** [MufasaTheMusician/eatwithme#39]
- [ ] Login refactor
- [ ] Map refactor
- [ ] Profile Card refactor
- [ ] Chatroom list refactor
- [ ] Chat refactor
- [ ] Edit Profile refactor

**Comment by MufasaTheMusician** [comment]
Testing notification in Slack

**Comment by MufasaTheMusician** [comment]
@MufasaTheMusician
